import { format } from "date-fns";
import { DefectRecord } from "@/components/defect-records/DefectRecord.types";

interface PrintDefectRecordsOptions {
  title?: string;
  getUserCode?: () => Promise<string | undefined>;
}

const groupRecordsByDate = (records: DefectRecord[]) => {
  const groups: { [key: string]: DefectRecord[] } = {};

  records.forEach((record) => {
    const dateKey = format(new Date(record.date), "yyyy-MM-dd");
    if (!groups[dateKey]) {
      groups[dateKey] = [];
    }
    groups[dateKey].push(record);
  });

  return Object.keys(groups)
    .sort((a, b) => new Date(b).getTime() - new Date(a).getTime())
    .map((dateKey) => ({
      date: dateKey,
      formattedDate: format(new Date(dateKey), "dd/MM/yyyy"),
      records: groups[dateKey],
    }));
};

export const printDefectRecords = async (
  records: DefectRecord[],
  options: PrintDefectRecordsOptions = {}
) => {
  if (records.length === 0) return;

  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) return;

  let userCode = "USER";
  if (options.getUserCode) {
    try {
      userCode = (await options.getUserCode()) || "USER";
    } catch (error) {
      console.error("Error getting user data:", error);
    }
  }

  const title =
    options.title ||
    `Defect Records Report - ${format(new Date(), "dd/MM/yyyy")}`;
  const groupedRecords = groupRecordsByDate(records);

  const printContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Defect Records Report</title>
        <style>
          @page {
            margin: 0.5in;
          }
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 10px;
            color: #000;
            font-size: 14px;
            line-height: 1.4;
          }
          .header {
            text-align: center;
            border-bottom: 1px solid #000;
            padding-bottom: 5px;
            margin-bottom: 10px;
          }
          .header h1 {
            margin: 0;
            font-size: 20px;
            font-weight: bold;
          }
          .header p {
            margin: 2px 0 0 0;
            font-size: 12px;
          }
          .date-group {
            margin-bottom: 15px;
          }
          .date-header {
            background: #f0f0f0;
            padding: 5px 8px;
            font-weight: bold;
            font-size: 12px;
            border: 1px solid #000;
            margin-bottom: 0;
          }
          .records-table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #000;
            margin-bottom: 10px;
            font-size: 11px;
          }
          .records-table th {
            background: #e0e0e0;
            color: #000;
            padding: 4px 6px;
            text-align: left;
            font-weight: bold;
            font-size: 10px;
            border: 1px solid #000;
          }
          .records-table td {
            padding: 4px 6px;
            border: 1px solid #000;
            font-size: 10px;
          }
          .records-table tr:nth-child(even) {
            background: #f9f9f9;
          }
          .checkbox {
            text-align: center;
          }
          .checkbox input {
            width: 12px;
            height: 12px;
            border: none !important;
            background-color: white !important;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            position: relative;
          }
          .checkbox input:checked {
            background-color: white !important;
          }
          .checkbox input:checked::after {
            content: "✓";
            position: absolute;
            top: -2px;
            left: 1px;
            color: black !important;
            font-size: 10px;
            font-weight: bold;
            text-shadow: none;
          }
          .checkbox input:checked::before {
            content: "✓";
            position: absolute;
            top: -2px;
            left: 1px;
            color: black !important;
            font-size: 10px;
            font-weight: bold;
            z-index: 1;
            text-shadow: none;
          }
          .no-records {
            text-align: center;
            padding: 20px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <p>Generated by ${userCode}</p>
        </div>

        ${
          records.length === 0
            ? `
          <div class="no-records">
            <p>No records found</p>
          </div>
        `
            : `
          ${groupedRecords
            .map(
              (group) => `
            <div class="date-group">
              <div class="date-header">
                ${group.formattedDate} (${group.records.length} Records)
              </div>
              <table class="records-table">
                <thead>
                  <tr>
                    <th>TIME</th>
                    <th>A/C</th>
                    <th>STA</th>
                    <th>DEFECT</th>
                    <th>REMARK</th>
                    <th>RST</th>
                    <th>DLY</th>
                    <th>OK</th>
                  </tr>
                </thead>
                <tbody>
                  ${group.records
                    .map(
                      (record) => `
                    <tr>
                      <td>${record.time}</td>
                      <td>${record.registration}</td>
                      <td>${record.station}</td>
                      <td>${record.defect}</td>
                      <td>${(record.remarks || "").toUpperCase()}</td>
                      <td class="checkbox">
                        <input type="checkbox" ${
                          record.rst ? "checked" : ""
                        } disabled />
                      </td>
                      <td class="checkbox">
                        <input type="checkbox" ${
                          record.dly ? "checked" : ""
                        } disabled />
                      </td>
                      <td class="checkbox">
                        <input type="checkbox" ${
                          record.ok ? "checked" : ""
                        } disabled />
                      </td>
                    </tr>
                  `
                    )
                    .join("")}
                </tbody>
              </table>
            </div>
          `
            )
            .join("")}
        `
        }
      </body>
    </html>
  `;

  printWindow.document.write(printContent);
  printWindow.document.close();

  printWindow.addEventListener("load", () => {
    setTimeout(() => {
      printWindow.document.body.offsetHeight;
      printWindow.print();

      const handlePrintComplete = () => {
        setTimeout(() => {
          if (printWindow && !printWindow.closed) {
            printWindow.close();
          }
        }, 1000);
      };

      printWindow.addEventListener("afterprint", handlePrintComplete);

      printWindow.addEventListener("beforeunload", () => {
        if (printWindow && !printWindow.closed) {
          printWindow.close();
        }
      });

      setTimeout(() => {
        if (printWindow && !printWindow.closed) {
          printWindow.close();
        }
      }, 1000);
    }, 1000);
  });
};
